org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=D:/android_studio/jbr
systemProp.java.net.useSystemProxies=false
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=false
