package com.componentvault.android.ui.screen.preview

import com.componentvault.android.ui.screen.CommonStrings
import com.componentvault.android.ui.screen.ComponentVaultStrings
import com.componentvault.android.ui.screen.FormsStrings
import com.componentvault.android.ui.screen.InventoryStrings
import com.componentvault.android.ui.screen.MovementsStrings
import com.componentvault.android.ui.screen.OverviewStrings
import com.componentvault.android.ui.screen.SettingsStrings
import com.componentvault.android.ui.screen.ShellStrings

internal object PreviewComponentVaultStrings {
    val Default = ComponentVaultStrings(
        shell = ShellStrings(
            appTitle = "Component Vault",
            inventoryDestination = "Inventory",
            movementsDestination = "Movements",
            overviewDestination = "Overview",
            settingsDestination = "Settings",
        ),
        common = CommonStrings(
            actionAdd = "Add",
            actionBack = "Back",
            actionCancel = "Cancel",
            actionDelete = "Delete",
            actionEdit = "Edit",
            actionHideToken = "Hide token",
            actionManageSync = "Manage sync",
            actionRecordMovement = "Record movement",
            actionSave = "Save",
            actionSaveSettings = "Save settings",
            actionShowToken = "Show token",
            actionSyncNow = "Sync now",
            actionTestConnection = "Test connection",
            actionViewInventory = "Open inventory",
            actionViewMovements = "View movements",
            emptyAllComponentsHealthy = "All active components are above minimum stock.",
            emptyNoComponentSelected = "No component selected yet.",
            emptyNoComponentsMatchFilter = "No components match the current filters.",
            emptyNoMovements = "No stock movements recorded yet.",
            labelNoDescription = "No description provided.",
            labelNoNote = "No note recorded.",
            labelNoReasonRecorded = "No reason recorded.",
            labelNotConfigured = "Not configured",
            labelUpdated = "Updated",
            statusLowStock = "Low stock",
            statusHealthy = "Healthy",
            fieldApiToken = "API token",
            fieldCategory = "Category",
            fieldComponent = "Component",
            fieldDescription = "Description",
            fieldLocation = "Location",
            fieldMinimumStock = "Minimum stock",
            fieldName = "Name",
            fieldNote = "Note",
            fieldPackage = "Package",
            fieldQuantity = "Quantity",
            fieldReason = "Reason",
            fieldServerUrl = "Server URL",
            fieldSku = "SKU",
        ),
        inventory = InventoryStrings(
            filtersTitle = "Search and filter",
            filtersSubtitle = "Narrow the list first, then inspect details or record changes.",
            searchLabel = "Search components",
            searchPlaceholder = "SKU, name, category, package, location",
            filterAll = "All",
            filterLowStock = "Low stock",
            filterCategoryLabel = "Category",
            filterCategoryAll = "All categories",
            filterLocationLabel = "Location",
            filterLocationAll = "All locations",
            filterSortLabel = "Sort",
            sortUpdatedNewest = "Recently updated",
            sortName = "Name A-Z",
            sortQuantityLowToHigh = "Quantity low to high",
            sortQuantityHighToLow = "Quantity high to low",
            resultsSummaryPattern = "Showing %1\$d items across %2\$d categories and %3\$d locations.",
            detailBasicTitle = "Basic info",
            detailStockTitle = "Stock status",
            detailLocationTitle = "Storage location",
            detailNotesTitle = "Description and notes",
            detailRecentMovementsTitle = "Recent movements",
            detailRecentMovementsEmpty = "No recent movement history for this component.",
            componentSubtitlePattern = "%1\$s | %2\$s | %3\$s",
            componentMinStockPattern = "Min %1\$d",
            selectedComponentTitle = "Component details",
            selectedComponentEmptySubtitle = "Select a row to inspect stock, storage, and recent changes.",
            selectedComponentLowStockStatus = "Restock recommended. Current stock is at or below minimum stock.",
            selectedComponentHealthyStatus = "Current stock is above the minimum stock threshold.",
            metricQuantity = "Quantity",
            metricMinStock = "Minimum stock",
        ),
        movements = MovementsStrings(
            recordTitle = "Record and history",
            recordSubtitle = "Capture the next stock change and keep working through recent history.",
            resultsSummaryPattern = "%1\$d records across %2\$d active components.",
            detailTitle = "Movement details",
            detailEmptySupporting = "Select a history row to inspect reason, note, and timestamp.",
            detailEmpty = "No movement selected yet.",
            detailHappenedAt = "Happened at",
            typeInbound = "Inbound",
            typeOutbound = "Outbound",
            typeAdjustment = "Adjustment",
            positiveQuantityPattern = "+%1\$d",
            updatedAtPattern = "Updated at %1\$s",
        ),
        overview = OverviewStrings(
            syncTitle = "Sync status",
            syncSubtitle = "Local writes happen first. Server sync stays on-demand.",
            lowStockSupporting = "Prioritize low stock items, then jump back into inventory work.",
            recentActivitySupporting = "Recent stock changes that can jump back into movement history.",
            inventoryHint = "The daily flow starts in Inventory: search first, filter second, then inspect or edit.",
            metricComponents = "Components",
            metricUnits = "Units",
            metricLowStock = "Low stock",
            metricMovements = "Movements",
            lowStockSectionTitle = "Low stock watchlist",
            recentActivitySectionTitle = "Recent activity",
        ),
        settings = SettingsStrings(
            summaryTitle = "Sync configuration",
            summarySubtitle = "Server connection, auth, and the latest sync result.",
            autoSync = "Auto sync",
            deviceId = "Device ID",
            endpoint = "Server endpoint",
            lastResult = "Latest result",
            lastSynced = "Last synced",
            formTitle = "Connection details",
            formSubtitle = "Save settings first, then test the connection or sync immediately.",
            serverUrlPlaceholder = "http://localhost:8787",
            autoSyncDescription = "Try syncing automatically on app launch and after local writes succeed.",
        ),
        forms = FormsStrings(
            addComponentTitle = "Add component",
            editComponentTitle = "Edit component",
            invalidQuantityMinStock = "Quantity and minimum stock must be valid integers.",
            recordStockMovementTitle = "Record stock movement",
            componentBasicTitle = "Basic identification",
            componentBasicSubtitle = "Used for quick search and location lookup.",
            componentStockTitle = "Stock threshold",
            componentStorageTitle = "Storage and notes",
            movementScopeTitle = "Movement scope",
            movementScopeSubtitle = "Select the component and movement type before entering quantity.",
            movementEntryTitle = "Movement details",
            deleteConfirmTitle = "Delete component?",
            deleteConfirmMessage = "This marks the component as deleted and pushes that state on the next sync.",
            movementEditorInstruction = "Use positive values for inbound and outbound. Adjustments may be positive or negative.",
            componentRequiredFields = "Fill in SKU, name, category, package, and location.",
            componentNonNegative = "Quantity and minimum stock cannot be negative.",
            chooseComponentTypeReason = "Select a component and movement type, then enter a reason.",
            adjustmentNonZero = "Adjustment quantity cannot be zero.",
            movementQuantityPositive = "Movement quantity must be greater than zero.",
        ),
    )

    val ZhCn = Default.copy(
        common = Default.common.copy(
            actionBack = "返回",
            actionDelete = "删除",
            actionEdit = "编辑",
            actionRecordMovement = "记录变动",
            emptyNoComponentSelected = "尚未选中任何元器件。",
            emptyNoComponentsMatchFilter = "当前筛选条件下没有匹配的元器件。",
            labelNoDescription = "暂无说明。",
            labelNoNote = "未填写备注。",
            labelNoReasonRecorded = "未填写原因。",
            labelUpdated = "更新时间",
            statusLowStock = "低库存",
            statusHealthy = "库存正常",
            fieldCategory = "分类",
            fieldLocation = "仓位",
            fieldName = "名称",
            fieldPackage = "封装",
            fieldQuantity = "数量",
            fieldReason = "原因",
            fieldNote = "备注",
            fieldSku = "SKU",
        ),
        inventory = Default.inventory.copy(
            filtersTitle = "搜索与筛选",
            filtersSubtitle = "优先收窄列表，再进入详情、编辑或记录变动。",
            searchLabel = "搜索元器件",
            searchPlaceholder = "SKU、名称、分类、封装、仓位",
            filterAll = "全部",
            filterLowStock = "仅低库存",
            filterCategoryLabel = "分类",
            filterCategoryAll = "全部分类",
            filterLocationLabel = "仓位",
            filterLocationAll = "全部仓位",
            filterSortLabel = "排序",
            sortUpdatedNewest = "最近更新",
            sortName = "名称 A-Z",
            sortQuantityLowToHigh = "库存从低到高",
            sortQuantityHighToLow = "库存从高到低",
            resultsSummaryPattern = "当前显示 %1\$d 条，覆盖 %2\$d 个分类和 %3\$d 个仓位。",
            detailBasicTitle = "基本信息",
            detailStockTitle = "库存状态",
            detailLocationTitle = "存放位置",
            detailNotesTitle = "描述与备注",
            detailRecentMovementsTitle = "最近变动",
            detailRecentMovementsEmpty = "该元件最近没有库存变动。",
            componentMinStockPattern = "最低 %1\$d",
            selectedComponentTitle = "元件详情",
            selectedComponentEmptySubtitle = "从列表中选中一项后，可查看库存、仓位和最近变动。",
            selectedComponentLowStockStatus = "建议补货。当前库存已低于或等于最低库存。",
            selectedComponentHealthyStatus = "当前库存高于最低库存阈值。",
            metricQuantity = "库存数量",
            metricMinStock = "最低库存",
        ),
    )
}
